# Generated by Django 3.1.7 on 2021-03-12 11:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inspec_user',
            fields=[
                ('user_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_pass', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('project_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('report_number', models.IntegerField(unique=True)),
                ('data_perform', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_user_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='projectReport.inspec_user')),
            ],
        ),
    ]
