# Generated by Django 3.1.7 on 2021-03-17 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('project_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('report_number', models.IntegerField(unique=True)),
                ('data_perform', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_user_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
