# Generated by Django 3.1.7 on 2021-03-17 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectReport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='location_discipline',
            fields=[
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('discipline_name', models.CharField(blank=True, max_length=200)),
                ('location_discipline_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='projectReport.project')),
            ],
        ),
    ]
