# Generated by Django 3.1.7 on 2021-03-17 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectReport', '0002_location_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='weld_action',
            fields=[
                ('during_welding', models.BooleanField(default=False)),
                ('before_welding', models.BooleanField(default=False)),
                ('after_welding', models.BooleanField(default=False)),
                ('weld_action_project_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='projectReport.project')),
            ],
        ),
    ]
