# Generated by Django 3.1.7 on 2021-03-12 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectReport', '0003_weld_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='heat_calc',
            fields=[
                ('current_A', models.IntegerField(blank=True, default=0)),
                ('voltage_V', models.IntegerField(blank=True, default=0)),
                ('time_SS', models.IntegerField(blank=True, default=0)),
                ('length_MM', models.IntegerField(blank=True, default=0)),
                ('heat_input', models.IntegerField(blank=True, default=0)),
                ('heat_calc_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='projectReport.project')),
            ],
        ),
    ]
