# Generated by Django 3.1.7 on 2021-03-12 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectReport', '0004_heat_calc'),
    ]

    operations = [
        migrations.CreateModel(
            name='drawing',
            fields=[
                ('drawing_number', models.CharField(max_length=200)),
                ('drawing_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='projectReport.project')),
            ],
        ),
    ]
