# Generated by Django 3.1.7 on 2021-03-17 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectReport', '0006_weld'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('photo_report_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='projectReport.project')),
            ],
        ),
    ]
