# Generated by Django 3.1.7 on 2021-03-12 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectReport', '0007_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity_description',
            fields=[
                ('act_descp', models.CharField(blank=True, max_length=200, primary_key=True, serialize=False)),
                ('act_descp_source', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='projectReport.inspec_user')),
            ],
        ),
    ]
