# Generated by Django 3.1.6 on 2021-03-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawing',
            name='id',
        ),
        migrations.RemoveField(
            model_name='location_discipline',
            name='id',
        ),
        migrations.RemoveField(
            model_name='weld',
            name='id',
        ),
        migrations.AlterField(
            model_name='drawing',
            name='drawing_number',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='photo_pics'),
        ),
        migrations.AlterField(
            model_name='location_discipline',
            name='location_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weld',
            name='weld_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
