# Generated by Django 3.1.7 on 2021-04-06 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='data_perform',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 0, 0, 38, 515081)),
        ),
    ]
