# Generated by Django 3.1.6 on 2021-03-30 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_auto_20210330_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weld_action',
            name='id',
        ),
        migrations.AlterField(
            model_name='weld_action',
            name='weld_action_project_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inspection.project'),
        ),
    ]
