# Generated by Django 3.1.6 on 2021-03-30 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0004_auto_20210330_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_inspection_action',
            name='act_desp_action_descp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.activity_description'),
        ),
        migrations.AlterField(
            model_name='activity_inspection_action',
            name='inspection_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inspection.project'),
        ),
    ]
