# Generated by Django 3.1.6 on 2021-03-30 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0006_auto_20210330_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='id',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='photo_report_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inspection.project'),
        ),
    ]
