# Generated by Django 3.1.7 on 2021-03-31 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0007_auto_20210330_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.ImageField(default='weld.png', upload_to='photo_pics'),
        ),
        migrations.AlterField(
            model_name='project',
            name='data_perform',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 1, 51, 8, 549589)),
        ),
    ]
